{{- if .Values.secret.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: yhs-secret
  namespace: yunikorn
  labels:
    app: yunikorn-history-server
    {{- with .Values.common.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  YHS_DB_PASSWORD: "{{ required "A valid .secret.dbPassword is required!" .Values.secret.dbPassword | b64enc }}"
{{- end }}