{{- $serviceType := .Values.service.type | required "A valid .Values.service.type is required!" -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "unicorn-history-server.fullname" . }}
  labels:
    {{- include "unicorn-history-server.labels" . | nindent 4 }}
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if eq $serviceType "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: http
      name: http
  selector:
    {{- include "unicorn-history-server.selectorLabels" . | nindent 4 }}
