{{- $dbPassword := .Values.db.password -}}
{{- $passwordSecretRef := .Values.db.passwordSecretRef -}}
{{- if and (not $dbPassword) (not $passwordSecretRef) }}
{{- fail "Either db.password or db.passwordSecretRef must be provided!" }}
{{- end }}

{{- $replicaCount := .Values.replicaCount | required "A valid .Values.replicaCount is required!" -}}
{{- $imageRegistry := .Values.image.registry | required "A valid .Values.image.registry is required!" -}}
{{- $imageRepository := .Values.image.repository | required "A valid .Values.image.repository is required!" -}}
{{- $imageTag := .Values.image.tag | required "A valid .Values.image.tag is required!" -}}
{{- $imagePullPolicy := .Values.image.pullPolicy | required "A valid .Values.image.pullPolicy is required!" -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "yunikorn-history-server"
  namespace: {{ .Values.common.namespace }}
  labels:
    app: yunikorn-history-server
    {{- with .Values.common.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ $replicaCount }}
  selector:
    matchLabels:
      app: "yunikorn-history-server"
  template:
    metadata:
      labels:
        app: yunikorn-history-server
        {{- with .Values.common.labels }}
        {{- toYaml . | nindent 4 }}
        {{- end }}
    spec:
      containers:
        - name: "yunikorn-history-server"
          image: "{{ $imageRegistry }}/{{ $imageRepository }}:{{ $imageTag }}"
          imagePullPolicy: "{{ $imagePullPolicy }}"
          envFrom:
            - configMapRef:
                name: yhs-config
          env:
            - name: YHS_DB_PASSWORD
              {{- if $passwordSecretRef }}
              valueFrom:
                secretKeyRef:
                  name: {{ $passwordSecretRef }}
                  key: YHS_DB_PASSWORD
              {{- else }}
              value: {{ $dbPassword | quote }}
              {{- end }}