{{- $serviceType := .Values.service.type | required "A valid .Values.service.type is required!" -}}
{{- $servicePort := .Values.service.port | required "A valid .Values.service.port is required!" -}}
{{- $serviceTargetPort := .Values.service.targetPort }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "yunikorn-history-server.fullname" . }}
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "yunikorn-history-server.labels" . | nindent 4 }}
    {{- with .Values.common.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ $serviceType }}
  ports:
    - port: {{ $servicePort }}
      {{- if $serviceTargetPort }}
      targetPort: {{ $serviceTargetPort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "yunikorn-history-server.selectorLabels" . | nindent 4 }}