{{- $dbPassword := .Values.db.password -}}
{{- $passwordSecretRef := .Values.db.passwordSecretRef -}}
{{- if and (not $dbPassword) (not $passwordSecretRef) }}
{{- fail "Either db.password or db.passwordSecretRef must be provided!" }}
{{- end }}

{{- $replicaCount := .Values.replicaCount | required "A valid .Values.replicaCount is required!" -}}
{{- $imageRegistry := .Values.image.registry | required "A valid .Values.image.registry is required!" -}}
{{- $imageRepository := .Values.image.repository | required "A valid .Values.image.repository is required!" -}}
{{- $imageTag := .Values.image.tag | required "A valid .Values.image.tag is required!" -}}
{{- $imagePullPolicy := .Values.image.pullPolicy | required "A valid .Values.image.pullPolicy is required!" -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yunikorn-history-server.fullname" . }}
  labels:
    {{- include "yunikorn-history-server.labels" . | nindent 4 }}
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $replicaCount }}
  selector:
    matchLabels:
      {{- include "yunikorn-history-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "yunikorn-history-server.labels" . | nindent 8 }}
        {{- with .Values.global.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: "yunikorn-history-server"
          image: "{{ $imageRegistry }}/{{ $imageRepository }}:{{ $imageTag }}"
          imagePullPolicy: "{{ $imagePullPolicy }}"
          args:
            - "--config"
            - "/app/config/config.yaml"
          volumeMounts:
            - mountPath: /app/config
              name: config
          env:
            - name: YHS_DB_PASSWORD
              {{- if $passwordSecretRef }}
              valueFrom:
                secretKeyRef:
                  name: {{ $passwordSecretRef }}
                  key: YHS_DB_PASSWORD
              {{- else }}
              value: {{ $dbPassword | quote }}
              {{- end }}
          ports:
            - containerPort: {{ .Values.yhs.port }}
              name: http
              protocol: TCP
      volumes:
        - name: config
          configMap:
            name: {{ include "yunikorn-history-server.fullname" . }}
