{{- if .Values.yhs.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "yunikorn-history-server.fullname" . }}-migrate
  labels:
    {{- include "yunikorn-history-server.labels" . | nindent 4 }}
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.global.annotations .Values.yhs.migrations.useHelmHooks }}
  annotations:
    {{- if .Values.yhs.migrations.useHelmHooks }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- end }}
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  template:
    metadata:
      labels:
        {{- include "yunikorn-history-server.labels" . | nindent 8 }}
        {{- with .Values.global.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: "yunikorn-history-server-migrate"
          image: "{{ include "yunikorn-history-server.image" . }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          args:
            - "migrate"
            - "up"
            - "--config"
            - "/app/config/config.yaml"
          volumeMounts:
            - mountPath: /app/config
              name: config
          env:
            - name: YHS_DB_PASSWORD
              {{- if .Values.db.passwordSecretRef }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.passwordSecretRef }}
                  key: YHS_DB_PASSWORD
              {{- else }}
              value: "{{ .Values.db.password }}"
              {{- end }}
      restartPolicy: Never
      volumes:
        - name: config
          configMap:
            name: {{ include "yunikorn-history-server.fullname" . }}
  backoffLimit: {{ .Values.yhs.migrations.backoffLimit}}
{{- end }}
