services:
  postgres:
    container_name: postgres
    image: postgres:15.7
    hostname: postgres
    # Either "linux/amd64" or "linux/arm64/v8" (e.g. Mac M1 systems)
    platform: linux/arm64/v8
    environment:
      - POSTGRES_PASSWORD=psw
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/init-database.sh
    healthcheck:
      test: /usr/local/bin/psql -U postgres -d postgres -c 'select now();'
      interval: 3s
      retries: 3
      start_period: 3s
      timeout: 10s
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=yhs@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5433:80"
    depends_on:
      - postgres
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - pgnetwork

networks:
  pgnetwork: