# -- Number of replicas for the deployment
replicaCount: 1

global:
  # -- Labels to add to all deployed resources
  labels: {}
  # -- Annotations to add to all deployed resources
  annotations: {}

image:
  # -- Docker registry
  registry: "docker.io"
  # -- Docker image repository
  repository: "gresearch/yunikorn-history-server"
  # -- Docker image tag
  tag: "main"
  # -- Docker image pull policy
  pullPolicy: "IfNotPresent"

service:
  # -- Service type
  type: ClusterIP
  # -- Service port
  port: 8989
  # -- Service target port
  targetPort: http

yhs:
  # -- YHS port
  port: 8989

db:
  # -- YHS database host
  host: "postgresql"
  # -- YHS database port
  port: "5432"
  # -- YHS database name
  name: "postgres"
  # -- YHS database user
  user: "postgres"
  # -- YHS database password (insecure, use secrets)
  password: "psw"
  # -- YHS database password secret reference
  passwordSecretRef: ""
  # -- Maximum number of connections in the database pool
  poolMaxConns: 0
  # -- Minimum number of connections in the database pool
  poolMinConns: 0
  # -- Maximum lifetime of a connection in the database pool
  poolMaxConnLifetime: 1800
  # -- Maximum idle time of a connection in the database pool
  poolMaxConnIdleTime: 120

yunikorn:
  # -- Yunikorn scheduler host
  host: "yunikorn-service"
  # -- Yunikorn scheduler port
  port: "9889"
  # -- Yunikorn scheduler protocol
  protocol: "http"

log:
    # -- Output type of the log, if true, log will be output in json format
    jsonFormat: true
    # -- Log level, one of DEBUG, INFO, WARN, ERROR, DPANIC, PANIC, FATAL
    level: "INFO"
